sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gFbpAX/qE1rth464hqQrGR/bLz6TIUX/Xp1/Y55LVN1+qFijYjtK5o/P/bxC/cqp2kXXKpT83fPTCvrMA/hdWe8x629lHeEBVV5aLl0NAVkGgGfq7coZS+VgzlXUrQMD91JUNM4zMREPzkYvbCs9LeGw0lOG54FzXhWTrLL9nOPmHu23RO8t9t+tQwCC6Uak0Pu0UUMI3ctKFarVcmxn7/AJS1oqmjQPj516sLcgDVaDuVLO4ALwbSajjqC5c7k8gQQjcLTfcClkqelpFJzptW/dFGajM9cBC9790RtpwaikUo0u2u093P6ifXCnppqzDVQEZxpHlFjePwP+/H325nmoDdajgUZxOKwh1tAAB1naFrKyr92aLwVBedOXRtz9sWd2ezy4PZkLwo7jgGM6e9yP+SCOHsO70hH/y6aqx+fa475ZUq8ZJKw+VmTQSOWP/8Hb6ZOlTPjUPwj8bDk205XCcF6DlGVRV+B7xxKexxrByRdmCpXxVdw7UYcaY4BsHukHE0iylsJYZY5IP4ky3/WrVc5xp8ccNzlj7ff6U5rsavqwPIAA9IuD/YbbFQIToFyA1x7SjRaW53Hdk0pGW6YJZD8dEbdPgEaA1px0p47sit45YDgA/uA+tp+lQ8I635ud/CVC5tx4CC2bBAfHz7x1Z8PFyX0edTzUterTet8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Latin-Vulgate-Esther--Liber-Esther_827
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy